### ISSUE TITLE
editorconfig-core-lua fails to build

### ISSUE THREAD

**Issue by bingalls** [editorconfig/editorconfig-core-lua#1]
I followed the README.md steps; I am running Mac OS X v10.13.
Note that I also had to (brew) install cmake
It failed on the step *cmake ..* with
 "tests/glob" which is not an existing directory.
 "tests/properties" which is not an existing  directory.
 "tests/parser" which is not an existing  directory.
 "tests/filetree" which is not an existing directory.
Further, these directories each need missing CMakeLists.txt

**Comment by randstr** [comment]
You need to pull the submodule contents using:
`git submodule init`
`git submodule update`

I agree the README.md should mention this, at least. It's not user-friendly right now.
